"""Constantes Messiah alineadas a enumeraciones Java."""

# EEstadoTrazabilidadAutorizacion
ESTADO_TRAZABILIDAD_EMITIDA = 1
ESTADO_TRAZABILIDAD_ACTIVADA = 2
ESTADO_TRAZABILIDAD_COMPLETADA = 3

# EEstadoFlujoAutorizacion
ESTADO_FLUJO_DIRECCIONADA = 0
ESTADO_FLUJO_ACTIVA = 1
ESTADO_FLUJO_CONFIRMADA = 2

# EContabiliza / ETipoDocumentoContable
CONTABILIZA_AUTORIZACIONES = 1
TIPO_DOCUMENTO_NOTA_AUTORIZACION = 1
PREFIJO_NOTA_AUTORIZACION = "NC-AT"

# ETypePreference
PREF_RESERVA_MEDICAMENTO_CONFIRMACION = 288
PREF_RESERVA_MEDICAMENTO_ACTIVACION = 390
PREF_VIGENCIA_MEDICAMENTOS = 6  # TP6 — vigencia activación/prestación medicamentos

# ETipoAccionLog / ETipoServicioLog
TIPO_ACCION_LOG_CONSULTA = 1
TIPO_ACCION_LOG_ACTIVACION = 4
TIPO_SERVICIO_LOG_MEDICAMENTO = 1

# EAuthorizationRequest.REQUEST_MEDICINES — orden médica IPS (tipo en ss_solicitud/ss_autorizacion)
TIPO_SERVICIO_SOLICITADO_MEDICAMENTOS = 6
SERVICIO_SOLICITUD_MEDICAMENTOS = "Medicamentos"

SW_LIBERADA_NO = 0

# EValorContabiliza
VALOR_CONTABILIZA_CERO = 0
VALOR_CONTABILIZA_TOTAL_MEDICAMENTOS = 92

# ERegimen (sc_contabiliza.tipo_regimen)
REGIMEN_CONTABILIZA_RS = 99
REGIMEN_CONTABILIZA_RC = 1

# ETipoAsiento
TIPO_ASIENTO_AUTORIZACION = 1

# ETipoTerceroContable
TERCERO_EPS = 1
TERCERO_PRESTADOR = 3
